HOW_STATUS=0

# NOTE redirections have to be done this way because:
# 1. Travis doesn't deploy symlinks (https://github.com/travis-ci/dpl/issues/912)
# 2. GitHub Pages uses symlinks to change the displayed page but the URL is not
#    updated. Since the links generated by html_of_wiki are relative and dependant
#    of the location of the file, the links from the redirected page are all wrong.
# `make-redir A B' creates B which redirects to A using `http-equiv'.
how-redirect() {
    cat >$2 <<EOF
<!DOCTYPE html>
<html>
    <head><meta http-equiv="refresh" content="0; URL=$1" /></head>
    <body></body>
</html>
EOF
}

how-redirect-manual() {
    local dir="$(pwd)/$HOW_OUT/$2"
    mkdir -p "$dir"
    cd "$HOW_OUT/$1"
    find . -type f | while read -r f; do
        mkdir -p `dirname "$dir/$f"`
        how-redirect "../../../$1/$f" "$dir/$f"
    done
    cd - 2>&1 >/dev/null
}

how-install() {
    export OCAML_VERSION=4.06
    export PACKAGE=
    wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
    bash -ex .travis-ocaml.sh
    eval $(opam env)

    git clone --depth 1 https://github.com/ocsigen/html_of_wiki.git
    opam pin add -y html_of_wiki html_of_wiki

    git clone --depth 1 https://github.com/ocsigen/ocsigen.github.io.git __ocsigen.github.io
    mv __ocsigen.github.io/template __ocsigen.github.io/how_template 
    mv __ocsigen.github.io/how_template .

    HOW_LATEST=$(find $HOW_DOC -maxdepth 1 -type d -not -name $HOW_DOC -not -name dev -exec basename {} \; | sort -nr | head -n 1)
    export HOW_LATEST
}

how-generate() {
    if ! quickdop -f $HOW_DOC $HOW_OUT -t json -c $HOW_CONFIG -viu; then
        HOW_STATUS=1
    fi
    return $HOW_STATUS
}
